import { firaSans, oswald, inter } from '@/font/font';
import './globals.scss';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${firaSans.variable} ${oswald.variable} ${inter.variable}`}>{children}</body>
    </html>
  )
}
