import { firaSans } from '@/font/font';
import './globals.scss';
import { Toaster } from 'react-hot-toast';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={firaSans.className}>
      <Toaster
          position="top-center"
          reverseOrder={false}
          toastOptions={{
            style: {
              borderRadius: '5px',
              borderColor:'#173D33',
              borderWidth:'1px',
              background: '#F3F5FA',
              color: '#173D33'
            },
            duration: 2500,
          }}
        />
        {children}
        </body>
    </html>
  )
}
